In [6]:
import torch
import torch.nn as nn
import torch.autograd

In [7]:
m = nn.Linear(20,30)
inputq = torch.autograd.Variable(torch.randn(128,20))
output = m(inputq)
print(output.size())

torch.Size([128, 30])


In [8]:
torch.randn(128,20)

tensor([[-0.6159,  0.2789,  1.3804,  ...,  0.7587,  0.6574, -1.1576],
        [-1.4799, -0.2942,  1.2202,  ..., -0.6812, -0.2769,  0.1958],
        [ 1.7215, -0.1954, -1.3470,  ..., -1.4516,  0.1574,  1.0629],
        ...,
        [ 0.9183, -0.1502,  1.1669,  ...,  0.2427,  1.3927, -0.5307],
        [ 1.0181, -1.1346,  0.4453,  ..., -0.4078, -0.5495,  0.5977],
        [ 0.6386, -0.5167, -0.4093,  ..., -2.0766,  0.0428, -1.6502]])

In [11]:
torch.zeros(21)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:

nn.Parameter(torch.ones(2))

Parameter containing:
tensor([1., 1.], requires_grad=True)

In [16]:
nn.Dropout(0.5)

Dropout(p=0.5)

In [6]:

    
    inputs = tf.to_int32(tf.reshape(tf.range(2*3), (2, 3)))
    outputs = embedding(inputs, 6, 2, zero_pad=True)
    with tf.Session() as sess:
        sess.run(tf.global_variables_initializer())
        print(sess.run(outputs))

W0920 11:56:10.477542 140652666222400 lazy_loader.py:50] 
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.



InternalError: cudaGetDevice() failed. Status: CUDA driver version is insufficient for CUDA runtime version

In [2]:
import tensorflow as tf

In [5]:
def embedding(inputs, 
              vocab_size, 
              num_units, 
              zero_pad=True, 
              scale=True,
              scope="embedding", 
              reuse=None):
    with tf.variable_scope(scope, reuse=reuse):
        lookup_table = tf.get_variable('lookup_table',
                                       dtype=tf.float32,
                                       shape=[vocab_size, num_units],
                                       initializer=tf.contrib.layers.xavier_initializer())
        if zero_pad:
            lookup_table = tf.concat((tf.zeros(shape=[1, num_units]),
                                      lookup_table[1:, :]), 0)
        outputs = tf.nn.embedding_lookup(lookup_table, inputs)
        
        if scale:
            outputs = outputs * (num_units ** 0.5) 
            
    return outputs

In [7]:
tf.__version__

'1.14.0'

In [8]:
pip list


Package              Version 
-------------------- --------
absl-py              0.7.1   
astor                0.8.0   
attrs                19.1.0  
backcall             0.1.0   
bleach               3.1.0   
certifi              2019.3.9
cffi                 1.12.3  
chardet              3.0.4   
cycler               0.10.0  
decorator            4.4.0   
defusedxml           0.6.0   
entrypoints          0.3     
gast                 0.2.2   
google-pasta         0.1.7   
gpt-2-simple         0.5.4   
gpt2-client          1.9.7   
grpcio               1.22.0  
h5py                 2.9.0   
idna                 2.8     
ipykernel            5.1.1   
ipyparallel          6.2.4   
ipython              7.7.0   
ipython-genutils     0.2.0   
ipywidgets           7.5.0   
jedi                 0.13.3  
Jinja2               2.10.1  
jsonschema           3.0.1   
jupyter-client       5.3.1   
jupyter-console      6.0.0   
jupyter-core         4.5.0   
Keras                2.2.5   
Keras-Appl

In [9]:
conda list

# packages in environment at /home/fengyuting/ls/envs/env_dialog:
#
_libgcc_mutex             0.1                        main  
_tflow_select             2.1.0                       gpu  
absl-py                   0.7.1                     <pip>
absl-py                   0.7.1                    py36_0  
astor                     0.8.0                     <pip>
astor                     0.8.0                    py36_0  
attrs                     19.1.0                   py36_1  
backcall                  0.1.0                    py36_0  
blas                      1.0                         mkl  
bleach                    3.1.0                    py36_0  
c-ares                    1.15.0            h7b6447c_1001  
ca-certificates           2019.5.15                     0  
certifi                   2019.3.9                 py36_0  
cffi                      1.12.3           py36h2e261b9_0  
chardet                   3.0.4                     <pip>
cudatoolkit               9.2         


Note: you may need to restart the kernel to use updated packages.
